# Fastlane requirements
fastlane_version "1.109.0"
generated_fastfile_id "0121e253-f9e2-40ac-b489-f17f36e24ec6"

import "./../Submodules/WeTransfer-iOS-CI/Fastlane/Fastfile"

desc "Parse the test results into the PR comment"
lane :parse_test_results do |options|
  # Set timeout to prevent xcodebuild -list -project to take to much retries.
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
  
  begin
    trainer(path: "#{ENV["$BITRISE_XCRESULT_PATH"]}", output_directory: "build/reports/", extension: ".xml", fail_build: false)
  rescue => ex
    UI.important("Trainer report generation failed #{ex}")
  end

  validate_changes(project_name: options[:project_name])
end
